apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h4jcsoi8a-go
  janus-idp.io/tekton: h4jcsoi8a-go
  backstage.io/kubernetes-id: h4jcsoi8a-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h4jcsoi8a-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
